import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        paddingHorizontal: 16,
        justifyContent: "space-between",
    },
    cameraContainer: {
        position: "relative",
        marginTop: 32,
        marginBottom: 8,
        height: 240,
        overflow: "hidden",
        backgroundColor: "#F6F6F6",
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "#E8E8E8",
        borderRadius: 8,
    },
    camera: {
        height: 240,
        justifyContent: "center",
        alignItems: "center",
    },
    cameraBtn: {
        width: 60,
        height: 60,
        borderRadius: 50,
        backgroundColor: "#FFFFFF",
        alignItems: "center",
        justifyContent: "center",
    },
    photoText: {
        marginBottom: 32,
        fontFamily: "Roboto-Regular",
        fontSize: 16,
        lineHeight: 19,
        color: "#BDBDBD",
    },
    input: {
        fontFamily: "Roboto-Regular",
        fontSize: 16,
        lineHeight: 19,
        height: 49,
        borderBottomWidth: 1,
        borderStyle: "solid",
        borderBottomColor: "#E8E8E8",
        borderStyle: "solid",
        backgroundColor: "#FFFFFF",
    },
    takePhotoContainer: {
        width: "100%",
        height: "100%",
        position: "absolute",
        borderColor: "#FFFFFF",
        borderWidth: 1,
    },
    sendBtn: {
        marginBottom: 100,
        justifyContent: "center",
        alignItems: "center",
        height: 51,
        backgroundColor: "#F6F6F6",
        borderRadius: 100,
    },
    btnTitle: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontSize: 16,
        lineHeight: 19,
        color: "#BDBDBD",
    },
    deleteBtn: {
        marginBottom: 34,
        width: 70,
        height: 40,
        marginLeft: "auto",
        marginRight: "auto",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#F6F6F6",
        borderRadius: 20,
    },
    iconNav: {
        width: 70,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
    },
});